Save evaluation results on csv file

diff --git a/train_pendulum_simple b/train_pendulum_simple
--- a/train_pendulum_simple
+++ b/train_pendulum_simple
@@ -6,6 +6,7 @@ N="$1"
 # Latent space dim:
 LSD=$(( 2 * N ))
 
+CSV_FILE="experiments/evaluation_error_simple.csv"
 OUTDIR="experiments/pendulum-simple/${N}"
 MODEL="simple[a=$LSD,b=116]"
 
@@ -23,8 +24,16 @@ date >> "$OUTDIR/progress.txt"
     "$MODEL"                                \
     "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"
 
+# Create CSV file with header if it does not exist
+if ! [ -f "$CSV_FILE" ]; then
+    echo "last_step;mean_error;last_error;model;n-links" >> $CSV_FILE
+fi
+
+{
 ./.colorize ./pendulum_error.py             \
     pendulum[n=$N,test]                     \
     "$MODEL"                                \
-    "$OUTDIR/checkpoint_*.pth"    \
-    1000 | tee -a "$OUTDIR/eval.txt"
+    "$OUTDIR/checkpoint_*.pth"              \
+    1000                                 && \
+    printf $";pendulum-simple;${N}\n";                                   
+} >> "$CSV_FILE"
diff --git a/train_pendulum_stable b/train_pendulum_stable
--- a/train_pendulum_stable
+++ b/train_pendulum_stable
@@ -12,6 +12,7 @@ REHU="$7"
 # Latent space dim:
 LSD=$(( 2 * N ))
 
+CSV_FILE="experiments/evaluation_error.csv"
 OUTDIR="experiments/pendulum-${EXP_ID}/${N}_${ALPHA}_${INNER}_${INNER_EPSILON}_${SMOOTH_V}_${REHU}"
 MODEL="stabledynamics[latent_space_dim=$LSD,a=$ALPHA,projfn=$INNER,projfn_eps=$INNER_EPSILON,smooth_v=$SMOOTH_V,hp=60,h=100,rehu=$REHU]"
 
@@ -29,8 +30,16 @@ date >> "$OUTDIR/progress.txt"
     "$MODEL"                                \
     "$OUTDIR/checkpoint_{epoch:0>5}.pth" | tee -a "$OUTDIR/progress.txt"
 
+# Create CSV file with header if it does not exist
+if ! [ -f "$CSV_FILE" ]; then
+    echo "last_step;mean_error;last_error;model;n-links;alpha;inner;inner_epsilon;smooth_v;rehu" >> $CSV_FILE
+fi
+
+{
 ./.colorize ./pendulum_error.py             \
     pendulum[n=$N,test]                     \
     "$MODEL"                                \
     "$OUTDIR/checkpoint_*.pth"              \
-    1000 | tee -a "$OUTDIR/eval.txt"
+    1000                                 && \
+    printf $";pendulum-${EXP_ID};${N};${ALPHA};${INNER};${INNER_EPSILON};${SMOOTH_V};${REHU}\n";                                   
+} >> "$CSV_FILE"
